name: Build Info with JFrog Integration

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  BUILD_NAME: spinnaker-build
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build-info:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Make Gradle wrapper executable
      run: chmod +x gradlew
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      with:
        version: 'latest'
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

    - name: Configure Gradle with JFrog
      run: |
        jf gradle-config  --repo-resolve=poc-maven-release --repo-deploy=poc-maven-release --use-wrapper
        
    - name: Install dependencies and build
      run: |
        jf gradle clean build artifactoryPublish --build-name=$BUILD_NAME --build-number=$BUILD_NUMBER --project=poc

    - name: Collect build environment
      run: |
        jf rt build-collect-env $BUILD_NAME $BUILD_NUMBER --project=poc
        
    - name: Collect VCS information
      run: |
        jf rt build-add-git $BUILD_NAME $BUILD_NUMBER --project=poc
        
    - name: Publish build info to Artifactory
      run: |
        jf rt build-publish $BUILD_NAME $BUILD_NUMBER --project=poc
        
    - name: Xray Build Scan
      run: |
        jf build-scan $BUILD_NAME $BUILD_NUMBER --format=table --fail=false --project=poc
      continue-on-error: true
    - name: Display build information
      run: |
        echo "### Build Information"
        echo "- **Build Name:** $BUILD_NAME"
        echo "- **Build Number:** $BUILD_NUMBER"
        echo "- **Timestamp:** $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "- **Commit SHA:** ${{ github.sha }}"
        echo "- **Short SHA:** ${GITHUB_SHA:0:7}"
        echo "- **Branch:** ${{ github.ref_name }}"
        echo "- **Repository:** ${{ github.repository }}"
        echo "- **Actor:** ${{ github.actor }}"
    
    - name: Create build info summary
      run: |
        mkdir -p build-artifacts
        cat > build-artifacts/build-summary.json << EOF
        {
          "build_name": "$BUILD_NAME",
          "build_number": "$BUILD_NUMBER",
          "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "commit_sha": "${{ github.sha }}",
          "commit_short_sha": "${GITHUB_SHA:0:7}",
          "branch_name": "${{ github.ref_name }}",
          "repository": "${{ github.repository }}",
          "actor": "${{ github.actor }}",
          "workflow_run_id": "${{ github.run_id }}",
          "artifactory_url": "${{ secrets.JF_URL }}"
        }
        EOF
    
    
    - name: Upload Gradle artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gradle-artifacts
        path: |
          build/libs/
          */build/libs/
        retention-days: 30
      if: always()